### ISSUE TITLE
An attempt to use the http client kills container.

### ISSUE THREAD

**Issue by shkuropat** [tarantool/docker#59]
> docker run --name mytarantool -d -p 3301:3301 tarantool/tarantool:1
docker exec -i -t mytarantool tarantoolctl connect '3301'

> url = 'https://pastebin.com/EqcLcXhZ'
http_client = require('http.client').new()
http_client:get(url)

Docker [log](https://pastebin.com/EqcLcXhZ)

Repeated on:
Ubuntu 18.04.1 LTS (Bionic Beaver)
Linux Mint 19 (Tara)
Linux Mint 18.2 (Sonya)

**Comment by Totktonada** [comment]
Likely is related to https://github.com/tarantool/tarantool/issues/3569

**Comment by Totktonada** [comment]
Cannot reproduce the issue. Can you please try this patch?

```diff
diff --git a/1.x/Dockerfile b/1.x/Dockerfile
index f1142d6..8f35da5 100644
--- a/1.x/Dockerfile
+++ b/1.x/Dockerfile
@@ -8,6 +8,8 @@ RUN addgroup -S tarantool \
 ENV TARANTOOL_VERSION=1.10.2-0-gc0d8063b6 \
     TARANTOOL_DOWNLOAD_URL=https://github.com/tarantool/tarantool.git \
     TARANTOOL_INSTALL_LUADIR=/usr/local/share/tarantool \
+    CURL_REPO=https://github.com/curl/curl.git \
+    CURL_TAG=curl-7_59_0 \
     GPERFTOOLS_REPO=https://github.com/gperftools/gperftools.git \
     GPERFTOOLS_TAG=gperftools-2.5 \
     LUAROCKS_URL=https://github.com/tarantool/luarocks/archive/6e6fe62d9409fe2103c0fd091cccb3da0451faf5.tar.gz \
@@ -40,11 +42,9 @@ RUN set -x \
         ncurses \
         libgomp \
         lua \
-        curl \
         tar \
         zip \
         libunwind \
-        libcurl \
         icu \
     && apk add --no-cache --virtual .build-deps \
         perl \
@@ -67,9 +67,17 @@ RUN set -x \
         libtool \
         linux-headers \
         go \
-        curl-dev \
         icu-dev \
         wget \
+    && : "---------- curl ----------" \
+    && mkdir -p /usr/src/curl \
+    && git clone "$CURL_REPO" /usr/src/curl \
+    && git -C /usr/src/curl checkout "$CURL_TAG" \
+    && (cd /usr/src/curl \
+        && ./buildconf \
+        && ./configure --prefix "/usr/local" \
+        && make -j \
+        && make install) \
     && : "---------- gperftools ----------" \
     && mkdir -p /usr/src/gperftools \
     && git clone "$GPERFTOOLS_REPO" /usr/src/gperftools \
```

**Comment by Totktonada** [comment]
It was pushed into `master` and `1.9.2`. It was NOT pushed into `1.9.1`, `1.10.0`, `1.10.2` and older branches / directories (1.5, 1.6, ...). It was NOT investigated whether 1.x-centos7 affected.

PR #71 was pushed into `1.9.2` then. It should not affect anything, because the patch idea is not in prevent installing libcurl from apk (it is installed anyway, because many packages, say cmake, depends on it and play its role at least during build), but the idea is that `/usr/local/lib` seems to have precedence over `/usr/lib` (don't sure about the reason).

If the fix does the work (nobody still answer me) we need to update all directories and branches consistently. There are two possible follow ups:

* If the fix does the work, we need to investigate whether 1.x-centos7 affected and update all branches / directories need the fix. It should be performed in sync with pipilenes we have on hub.docker.com.
* If the fix does not the work, we need to revert all changes were performed within this scope.

**Comment by shkuropat** [comment]
Now docker not killing, but now has new interesting problem for url 'https://www.google.com/'
localhost:3301> http_client:get(url)
---
- error: 'curl: Problem with the SSL CA cert (path? access rights?)'
...

PS: All times use image from official docker repo

**Comment by Totktonada** [comment]
@shkuropat Can you please mention the specific docker tag you are use (default is `latest`) **and** version of tarantool (it is reported at start)? It is important to know where the original problem disappears (because I cannot reproduce it).

I reproduced the second problem and will investigate it.

**Comment by Totktonada** [comment]
`verify_peer = false` can be added as the temporary workaround.

**Comment by Totktonada** [comment]
The same for curl and wget within the image:

```
# curl -v -D - https://google.com
* Rebuilt URL to: https://google.com/
*   Trying 173.194.44.37...
* TCP_NODELAY set
* Connected to google.com (173.194.44.37) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

# wget -qO - https://google.com
wget: SSL/TLS certificate is not being validated!
```

**Comment by Totktonada** [comment]
`apk add --no-cache ca-certificates` helps me with that.

**Comment by shkuropat** [comment]
As I said in start topic, image tag is "1"
```
docker run --name mytarantool -d -p 3301:3301 tarantool/tarantool:1
```
Tarantool version
```
localhost:3301> require('tarantool').version
---
- 1.10.2-0-gc0d8063b6
...

**Comment by Totktonada** [comment]
Now all relevant branches are updated and will be built soon. Status of builds can be seen [here][1].

[1]: https://hub.docker.com/r/tarantool/tarantool/builds/
