### ISSUE TITLE
DNS not resolving

### ISSUE THREAD

**Issue by donmikel** [tarantool/docker#9]
`cat /etc/resolv.conf`

```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.3.0.10
options ndots:5
```

**Comment by racktear** [comment]
In musl libc there are a few differences from libc in how it handles resolv.conf.

Until recently, 'search' wasn't supported at all, though in alpine 3.4 it has been implemented.

Also, the nameservers get queried in parallel, instead of sequential, and the first result is returned.

People report that there are still issues with alpine+kubernetes. Please try rearranging 'search' entries in reverse order and see if it helps.

**Comment by donmikel** [comment]
Thanks, for help, this was a bug in the network settings, after correction, all the tests in Alpine:3.4 were successful.
